<?php
include ('Employee.php');
$employees = array(
		"Employee1" => new Employee(
				/*First Name*/	"John",
				 /*Last Name*/	"Alabastser",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	true,
				    /*Form B*/	true,
				    /*Form C*/	true,
				    /*Form D*/	true,
		       /*Form Total Progress*/  100),

		"Employee2" => new Employee(
				/*First Name*/	"Bill",
				 /*Last Name*/	"Brickman",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	false,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  20),

		"Employee3" => new Employee(
				/*First Name*/	"Charles",
				 /*Last Name*/	"Linda",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	true,
				    /*Form D*/	true,
		       /*Form Total Progress*/  80),

		"Employee4" => new Employee(
				/*First Name*/	"Danforth",
				 /*Last Name*/	"Kyle",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	false,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  10),

		"Employee5" => new Employee(
				/*First Name*/	"Gregory",
				 /*Last Name*/	"Karen",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  60),

		"Employee6" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  2),

		"Employee7" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  100),

		"Employee8" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  80),

		"Employee9" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  15),

		"Employee10" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  90),

		"Employee11" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  5),

		"Employee12" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  30),

		"Employee13" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  55),

		"Employee14" => new Employee(
				/*First Name*/	"First",
				 /*Last Name*/	"Last",
				 /*Job Title*/	"Job Title",
				  /*Benefits*/	"Package A",
				  /*Pay Rate*/	"$0 per year",
			   /*Hours this Week*/  0,
			   /*Hours last Week*/  0,
		  	     /*Average Hours*/  0,
			  /*Vacation Accrued*/	"0 hours",
				    /*Form A*/	false,
				    /*Form B*/	true,
				    /*Form C*/	false,
				    /*Form D*/	false,
		       /*Form Total Progress*/  87),
	);
?>
